### ISSUE TITLE
IISExpress: Support multiple projects with custom domain name

### ISSUE THREAD

**Issue by kedde** [CZEMacLeod/C3D.Extensions.Aspire#29]
Thanks for the package. 

in our setup we have multiple custom domains (e.g. api.domain.com and web.domain.com) and would like to be able to run these projects at the same time. When trying to do this we end up getting the following error:

"Port {port} is already allocated

As a temporary workaround I modified the method AddOrUpdateEndpointFromBinding - and doesn't mark the port as used when using a custom domain. But I guess the correct way would be to look at both port and domain name when checking if the port is used? 

``` CSharp
// AddOrUpdateEndpointFromBinding 
//...
var bindingDomain = binding.GetDomain();
var shouldMarkPortAsUsed = string.IsNullOrEmpty(bindingDomain) || bindingDomain == "localhost";
if (shouldMarkPortAsUsed)
{
    MarkPortAsUsed(binding.Port);
}
else
{
    logger.LogInformation("Not marking port as used - custom domain {BindingDomain} ", bindingDomain);
}

// ... added an extension method
public static string GetDomain(this Binding binding)
  {
      if (binding.BindingInformation is null)
      {
          return "";
      }

      // Extract the domain from the binding information
      var parts = binding.BindingInformation.Split(':');
      if (parts.Length < 3)
      {
          return "";
      }

      return parts[2]; // The domain is the third part
  }

// .... small unit test for the extension code
[Theory]
[InlineData("*:80:", "")]
[InlineData("192.168.0.1:80:www.contoso.com", "www.contoso.com")]
[InlineData("192.168.0.1:80:contoso.com", "contoso.com")]
[InlineData("*:443:", "")]
[InlineData(":443:api.domain.com", "api.domain.com")]
[InlineData(":443:web.domain.com", "web.domain.com")]
[InlineData(":44300:localhost", "localhost")]
[InlineData("*:51394:app.api.local", "app.api.local")]
public void GetDomainFromBindingInformation(string bindingInformation, string expected)
  {
      // Arrange
      var expectedDomain = expected;

      // Act
      var binding = new Binding
      {
          BindingInformation = bindingInformation
      };
      var actualDomain = binding.GetDomain();

      // Assert
      Assert.Equal(expectedDomain, actualDomain);
  }
```

if you like to support this feature - I am willing to create a PR - but would need some pointers on how you would like to support it?

**Comment by CZEMacLeod** [comment]
Hi - I like the general thought behind this, and we could certainly include some of this in the package, but while it makes sense from an IIS / Framework perspective, it does not adhere to the Aspire model.

Under aspire, every project runs on localhost only (and if using SSL then every project trusts the dev cert). This means that each project gets allocated random ports to run on, and random proxy ports in the DCP runtime.

The idea is that you pass then generated endpoint of your api project to your web project as a configuration parameter (via environment variables) and it gets hooked up that way. Or you can use the service discovery system to bind the httpclient to http://api/ and it resolves api under the covers to localhost:xxxx where xxxx is the proxy port. There is then a proxy so that even if the api has not yet started, the port can connect (then timeout).

This is kind of a fundamental shift in thinking (which took me a while to get) in designing with multiple services, and working inside aspire. Similarly, you might spin up a sql server instance in docker, which will again get random localhost ports each time, and pass that to the api project.

While it is true that when running with an existing applicationHost.config file, it will bind and run on custom host names, it is not the aspire way.
This is (partly) why there is the `.WithTemporaryConfig()` and `WithDefaultIISExpressEndpoints()` methods. This allows it to ignore the config file that would be used when running the project directly, and not mind if the project path changes (such as on a build server for tests).
It also means you don't have to have actual ssl certificates for your services installed, or hack the hosts file to override your production urls to point to your local machine.

I think it would probably be a good idea to add an example of with 2 IIS projects connected up to better convey this. You can see part of what I'm talking about in the SWA example (although this is a asp.net core frontend and a framework backend, but it does follow the same pattern).

It is certainly true that when marking ports as in use - it should only do so for localhost ports - so that part of the code does need a fix.

Let me think about what would be needed in a PR and what scenarios actually need support.

**Comment by CZEMacLeod** [comment]
I've pushed some changes in [fix-iis-customdomain-29](https://github.com/CZEMacLeod/C3D.Extensions.Aspire/tree/fix-iis-customdomain-29)

As I said before - aspire doesn't really cope well with the concept of multiple things on a single port, but the endpoint does include the target host for listening on, so this _might_ work.

I will need to try and build some kind of sample and test to cover this, but I feel it will be rather harder to run on a test server than the current stuff.

**Comment by kedde** [comment]
Hi

Thanks for answering so quickly and providing a solution, but still get this error: 

``` csharp
fail: C3D.Extensions.Aspire.IISExpress.IISEndPointConfigurator[0]
      An error occured configuring task: Port 443 is already allocated
      System.InvalidOperationException: Port 443 is already allocated
         at Aspire.Hosting.IISExpressEntensions.MarkPortAsUsed(Int32 port)
         at Aspire.Hosting.IISExpressEntensions.AddOrUpdateEndpointFromBinding(IResourceWithEndpoints resource, Binding binding)
         at C3D.Extensions.Aspire.IISExpress.IISEndPointConfigurator.AddBindings(IISExpressProjectResource project, SiteArgumentAnnotation site, ConfigArgumentAnnotation cfg)
         at C3D.Extensions.Aspire.IISExpress.IISEndPointConfigurator.ConfigureIISExpressProjectResource(String appHostConfig, IISExpressProjectResource project)
         at C3D.Extensions.Aspire.IISExpress.IISEndPointConfigurator.Configure()
```

I think we should change the condition from "!=" to "==" so the port is marked as used when localhost and not the otherway around. 

https://github.com/CZEMacLeod/C3D.Extensions.Aspire/commit/72903d61021351a36a9f2a41f17ca84ba2909241#diff-6795cac805f42050a38f29acaf018516161041fd4f514a24ce76cdbb299ccfabR344

``` csharp
    if (hostName != "localhost")
        {
            MarkPortAsUsed(binding.Port);
        }
```

Making change as described above - solves my issue.

**Comment by CZEMacLeod** [comment]
Good catch with the hostName logic - you are absolutely right there - it should only mark the port as used if it is listening on localhost.
Technically, only applications using httpsys (such as iis express) can share ports by host header like this (which is why you need to run `iisExpressAdminCmd.exe` as admin to update the kernel level bindings).
If using the port allocator for running tests in parallel (such as in the playwright example), then you wouldn't want to use the port for an asp.net core project, or any other purpose.

**Comment by CZEMacLeod** [comment]
One thing that might not work in this scenario, is that the proxied endpoints supplied by DCP/Aspire would have the 'wrong' hostname and thus not match. In this case, we should not enable the proxy and return the explicit binding/endpoint as-is to any external service.
I've updated the code to log a warning if it detects multiple things listening on a single port, and to disable the proxy for the endpoint if it is not using localhost. This should also make the links in the dashboard work correctly.
I think it would be good to have a couple of examples and tests to cover this. One with custom bindings, and one with two IIS Express projects linked up in a more Aspire style.
It would probably be possible to do this with a single host project, and use combinations of `WithTemporaryConfig` and `WithDefaultIISExpressEndpoints` methods to run the tests in the different modes. I think the one using host headers would have to be 'manual' and not run on the build server as I don't think there would be a good/easy way of handling that.
